flacjacket/pywlroots

- wlroots/wlr_types/keyboard.py
This is a simple change but seems to work... is nothing else required to do this?
> Expose keyboard destroy event

- wlroots/backend.py
- wlroots/ffi_build.py
This adds wlr_session_change_vt to the lib, and a Session class to use
it. The current Session can be obtained using wlr_backend_get_session
via Backend.get_session().
> Add Session class and expose wlr_session_change_vt

- tiny/server.py
- wlroots/backend.py
- wlroots/ffi_build.py
- wlroots/wlr_types/keyboard.py
- wlroots/wlr_types/output.py
A couple changes were left out when updating to use wlroots 0.13.0.
These are some others that are part of that release.
> Fixes to wlroots 0.13.0

- wlroots/ffi_build.py
- wlroots/renderer.py
- wlroots/wlr_types/box.py
- wlroots/wlr_types/texture.py
Namely a classmethod wrapper around `wlr_texture_from_pixels` and `wlr_render_texture`.
> Add more Texture handlers

- wlroots/ffi_build.py
- wlroots/wlr_types/__init__.py
- wlroots/wlr_types/xdg_output_v1.py
This adds a wrapper class for wlr_xdg_output_manager_v1 so that
compositors can support this protocol.
> Add wlr_xdg_output_manager_v1 support

- wlroots/ffi_build.py
- wlroots/wlr_types/__init__.py
- wlroots/wlr_types/gamma_control_v1.py
This adds parts of wlr/types/wlr_gamma_control_v1.h so that the gamma
control protocol can be support by compositors.
> Add wlr_gamma_control_manager_v1 support

- wlroots/__init__.py
Minor and micro are the wrong way round
> Fix version part order

- wlroots/ffi_build.py
- wlroots/wlr_types/__init__.py
- wlroots/wlr_types/data_control_v1.py
This is used by some clients for clipboard functionality.
> Add wlr_data_control_v1 interface

- wlroots/wlr_types/xdg_shell.py
This returns toplevel parent surfaces as XdgSurfaces
> Add parent method to xdg-shell toplevels

- wlroots/wlr_types/input_device.py
This adds wlr_input_device InputDevice properties to get vendor, product
and device name.
> Expose some input-device info properties

- wlroots/wlr_types/__init__.py
- wlroots/wlr_types/pointer_constraints_v1.py
> Fix duplicated typo: s/Contraints/Constraints

- wlroots/ffi_build.py
- wlroots/wlr_types/export_dmabuf_v1.py
Merging this will help with vulkan renderer screenshots if I'm not mistaken.
> [protocol] wlr_export_dmabuf_v1 bindings added.

- wlroots/ffi_build.py
- wlroots/wlr_types/__init__.py
- wlroots/wlr_types/viewporter.py
Signed-off-by: Shinyzenith <aakashsensharma@gmail.com>
> [bindgen] wlr_viewporter

- wlroots/wlr_types/input_inhibit.py
This requires https://github.com/flacjacket/pywayland/pull/39
> Wrap input inhibitor active client in pywayland Client

- tiny/server.py
- wlroots/allocator.py
- wlroots/renderer.py
- wlroots/wlr_types/layer_shell_v1.py
- wlroots/wlr_types/output_management_v1.py
- wlroots/wlr_types/pointer.py
- wlroots/wlr_types/seat.py
- wlroots/wlr_types/texture.py
- wlroots/wlr_types/xdg_shell.py
> Replaced classmethod decorator with staticmethod if the class variable is not used

- wlroots/ffi_build.py
- wlroots/wlr_types/session_lock_v1.py
> Added support for session_lock v1. Closes #157

- CHANGES.rst
- MANIFEST.in
I wasn't sure which format you preferred, since the README already uses reStructuredText, I used that format as well.
Closes #139
> Proposal for a changelog. Closes #139

- wlroots/wlr_types/pointer.py
> Pointer: Provide data property. Closes #173

- wlroots/wlr_types/touch.py
Touch inherits from PtrHasData instead of Ptr now.
Closes #178
> Added missing Touch.data property

- CHANGES.rst
Updated CHANGES to reflect latest (merged) PRs
> Updated CHANGES for 0.16.7

- wlroots/ffi_build.py
- wlroots/wlr_types/switch.py
Added Switch class as a wrapper for wlr_switch, added SwitchToggleEvent
and SwitchType and SwitchState enums
> Support for wlr_switch

- CHANGES.rst
Updated CHANGES for another 0.16 release.
> Updated CHANGES for 0.16.8

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Mitigate zlib AttributeError problem (check [this commit](https://github.com/pypy/pypy/commit/e884ecc9d2c4ff7fd1bb797695d32f67d5d81348)).
- Soon 3.10 will be dropped (as stated "[In the next release we will drop 3.10](https://doc.pypy.org/en/latest/release-v7.3.19.html)" by pypy)
> fix: move to pypy 3.11
