wlroots/wlr_types/xdg_shell.py
This adds methods to the XdgSurface class that wrap
wlr_xdg_toplevel_set_tiled and wlr_xdg_toplevel_set_fullscreen
functions.
=> Add set_tiled and set_fullscreen to Xdg_surface class

wlroots/wlr_types/xdg_shell.py
Apologies, in a previous commit I copy-pasted some lines when amending the commit before submission and it got merged with the typo. the `fullscreened` arg is for the previous method, and `xdg_toplevel_send_close` is a function used internally to wlroots via `wlr_xdg_toplevel_send_close`, which is what we should use.
=> Fix typos in XdgSurface.send_close

wlroots/wlr_types/seat.py
This avoids user code needing to check seat._ptr directly.
=> Add a property to Seat to determine if it has been destroyed

wlroots/__init__.py, wlroots/backend.py, wlroots/renderer.py, wlroots/util/clock.py, wlroots/wlr_types/compositor.py, wlroots/wlr_types/cursor.py, wlroots/wlr_types/data_device_manager.py, wlroots/wlr_types/input_device.py, wlroots/wlr_types/keyboard.py, wlroots/wlr_types/matrix.py, wlroots/wlr_types/output.py, wlroots/wlr_types/output_layout.py, wlroots/wlr_types/pointer.py, wlroots/wlr_types/seat.py, wlroots/wlr_types/surface.py, wlroots/wlr_types/texture.py, wlroots/wlr_types/xcursor_manager.py, wlroots/wlr_types/xdg_shell.py
This implements __eq__ in a Ptr base class that is passed to other
classes that can use it to test between their respective `self._ptr`
attributes. This means that new class instances created as part of class
properties (e.g. `Seat.keyboard` which creates a new instance of
`Keyboard`) can be compared with existing instances that represent the
same thing (i.e. have the same pointer).
--
This does appear to break the hashability of the classes, which breaks the weak referencing:
```
File "/home/mcol/git/qtile/libqtile/backend/wayland/keyboard.py", line 55, in __init__
self.keyboard = device.keyboard
File "/home/mcol/git/pywlroots/wlroots/wlr_types/input_device.py", line 55, in keyboard
_weakkeydict[keyboard] = self._ptr
File "/usr/lib/python3.9/weakref.py", line 418, in __setitem__ …
```
=> Implement equality testing for classes with _ptr pointers

wlroots/ffi_build.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/screencopy_v1.py
This adds some wlr_screencopy_v1.h content and a class that allows for
creating of a wlr_screencopy_manager_v1 instance via
wlr_screencopy_manager_v1_create. This is sufficient for basic screen
copying functionality.
=> Add wlr_screencopy_v1 interface

wlroots/ffi_build.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/virtual_keyboard_v1.py
This exposes parts of wlr_virtual_keyboard_v1.h and implements their
interface so that compositors can support virtual keyboards as inputs.
--
I'm not sure I did the weak referencing correctly. Is these the right things that need storing in the dict? I tried replicating from other files though I'm not sure I understand it fully.
=> Add wlr_virtual_keyboard_v1 support

tiny/__main__.py, tiny/server.py, wlroots/backend.py, wlroots/ffi_build.py, wlroots/helper.py, wlroots/renderer.py
The renderer can now be extracted from the backend. Change the constructor of the renderer to not need a Display, and add the display setup functionality to the compositor setup helper.
=> Add helper to setup compositor

wlroots/ffi_build.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/xdg_decoration_v1.py
This adds wlr/types/wlr_xdg_decoration_v1.h content and handlers so that
client surfaces can request client or server side window decorations,
and the server can tell windows which to use.
=> Expose wlr_xdg_decoration_v1 interface

tiny/server.py, wlroots/ffi_build.py, wlroots/renderer.py, wlroots/util/region.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/output.py, wlroots/wlr_types/output_damage.py
This adds an interface for `struct wlr_output_damage`, a corresponding
class OutputDamage, whose methods map onto the various functions that
operate on this struct.
This also adds a class wrapper around `pixman_region32_t` (already
included in the ffi_build C definition) for use by some of these
methods.
=> Add wlr_output_damage interface

wlroots/__init__.py, wlroots/ffi_build.py, wlroots/util/region.py, wlroots/wlr_types/box.py, wlroots/wlr_types/cursor.py, wlroots/wlr_types/gamma_control_v1.py, wlroots/wlr_types/input_device.py, wlroots/wlr_types/keyboard.py, wlroots/wlr_types/layer_shell_v1.py, wlroots/wlr_types/output.py, wlroots/wlr_types/output_damage.py, wlroots/wlr_types/output_layout.py, wlroots/wlr_types/output_management_v1.py, wlroots/wlr_types/screencopy_v1.py, wlroots/wlr_types/seat.py, wlroots/wlr_types/surface.py, wlroots/wlr_types/xdg_decoration_v1.py, wlroots/wlr_types/xdg_shell.py
This first lets PixmanRegion32 and Box be instantiated using pointers to objects that already exist, rather than creating new instances of these structs when instantiating the class.
The the third commit adds handlers for the various structs and methods in wlroots'
wlr_output_management_v1.h. This lets compositors create output managers
and process client requests to change the output layout and
configuration of each output. The output layout and output interfaces
have been extended somewhat to allow for the interaction between these
and the output manager objects.
=> Implement wlr output management v1

wlroots/wlr_types/output.py
This was a typo left in from copy-pasting the `set_mode` method.
`set_custom_mode` should only take width, height and refresh.
--
Should this not have been picked up by the CI as an unused argument?
=> Output.set_custom_mode should not have a `mode` argument

wlroots/ffi_build.py, wlroots/wlr_types/texture.py
This adds the above function to ffi_build.py and a corresponding method
to `Texture`. This lets you modify pixels in a mutable `Texture`.
=> Add wlr_texture_write_pixels to lib

wlroots/ffi_build.py, wlroots/wlr_types/server_decoration.py
This adds an interface to wlr/types/wlr_server_decoration.h. Only the
core part, the server decoration manager, is added, as this is sufficent
for most compositor use-cases to allow for clients using this protocol
to detect whether they should be using server or client-side
decorations. This wlroots interface is becoming deprecated in a future
version of wlroots (not necessarily the next version). However, this
will not happen until GTK, which uses this protocol, updates to the
alternative xdg_decoration. Until these updates have been done, this
protocol is useful to keep window decorations consistent.
=> Implement wlr_server_decoration with bare manager

wlroots/wlr_types/surface.py
Also exposes its events and surface so that compositors can listen to
these, useful for damage tracking.
=> Add class to represent wlr_subsurface

wlroots/ffi_build.py
The use of this enum was replaced with a uint32_t upstream for 0.13.0
=> Remove wl_shm_format

wlroots/ffi_build.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/primary_selection_v1.py
This adds PrimarySelectionV1DeviceManager to represent and wrap the
wlroots function wlr_primary_selection_v1_device_manager_create, which
implements a primary selection clipboard used by clients such as some
terminals.
=> Add interface for wlr_primary_selection_v1

wlroots/__init__.py, wlroots/wlr_types/output.py, wlroots/wlr_types/xdg_shell.py
This makes char array struct members that are exposed as class
properties return None when they are a null pointer, rather than
erroring on `ffi.string(ffi.NULL)`.
=> Add str_or_none helper function

wlroots/ffi_build.py, wlroots/wlr_types/input_device.py
This adds two functions from backend/libinput.h that are used to get the
libinput device handles from wlr_input_devices. These can be used to
configure these input devices using libinput-interfacing code.
=> Expose input device libinput handles

wlroots/ffi_build.py
This updates to 0.14 which changes the subsurfaces members of
wlr_surface to:
// wlr_subsurface.parent_link
struct wl_list subsurfaces_below;
struct wl_list subsurfaces_above;
// wlr_subsurface.parent_pending_link
struct wl_list subsurfaces_pending_below;
struct wl_list subsurfaces_pending_above;
=> Split wlr_surface.subsurfaces into two list per upstream

wlroots/backend.py, wlroots/wlr_types/output.py
These are properties return True when wlroots is running headlessly.
=> Add is_headless properties to Output and Backend

wlroots/wlr_types/output_layout.py
This function, when passed NULL rather than a wlr_output, returns the
wlr_box for the entire output layout. We should let this also work for
None on the Python side.
=> Let wlr_output_layout_get_box return extents of whole layout

.github/workflows/ci.yml, tests/conftest.py, tests/test_display.py
This is currently failing because of some issue launching the headless backend on the CI servers, but passes locally.
=> Add basic test to launch headless backend

wlroots/util/box.py
This Adds a `closest_point` method to `Box` that uses
`wlr_box_closest_point`, exposing this wlroots function to the Python
interface.
=> Add Box.closest_point() (and __repr__)

wlroots/ffi_build.py, wlroots/wlr_types/xdg_shell.py
This adds the `wlr_xdg_surface_configure` struct, which is emitted by
xdg toplevels as part of their `configure` and `ack_configure` events.
These can be used by compositors to synchronise state changes with
clients.
=> Add wlr_xdg_surface_configure and corresponding events

tiny/view.py, wlroots/renderer.py, wlroots/util/region.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/matrix.py, wlroots/wlr_types/output_damage.py, wlroots/wlr_types/output_layout.py, wlroots/wlr_types/xdg_shell.py
This stops pywlroots from emitting the warning itself when `wlr_types`
is being imported correctly.
=> Redirect internal Box import

wlroots/ffi_build.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/relative_pointer_manager_v1.py
This adds some of the code from wlroots' wlr_relative_pointer_v1.h so
that compositors can use the relative_pointer_v1 protocol.
=> Add wlr_relative_pointer_v1

wlroots/ffi_build.py, wlroots/wlr_types/data_device_manager.py, wlroots/wlr_types/seat.py
This exposes some more of the wlroots API for drag-and-dropping, which
is implemented as part of the seat. The exposed objects together enable
compositors to implement drag-and-drop within and between clients.
=> Add interface for wlr_drag and related objects

wlroots/ffi_build.py, wlroots/wlr_types/cursor.py, wlroots/wlr_types/seat.py, wlroots/wlr_types/touch.py
This adds some basic touch event methods to for wlr_seat, as well as the
touch events from wlr_touch.h. These can be used for compositors to
receive touch events.
=> Add some touch event handling to the seat

wlroots/ffi_build.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/foreign_toplevel_management_v1.py
This adds some code for wlroots' wlr_foreign_toplevel_management_v1
protocol so that compositors can expose window information and clients
can get information on other windows.
=> Add some handlers for wlr_foreign_toplevel_management_v1

wlroots/__init__.py
Some struct members are meant to be UTF-8 encoded strings, but bugs in
other software (i.e. clients) can cause them to provide invalid UTF-8
strings. This causes `UnicodeDecodeError` to be raised when decoding
these to Python strings. This change prevents these errors so that users
of pywlroots don't all need custom logic for bugs in other software.
--
See https://github.com/qtile/qtile/issues/3161 for more info. Qtile (and other pywlroots-using code) could instead catch the `UnicodeDecodeError` exceptions themselves as an alternative, or they could use `wlroots.ffi.string(obj._member).decode(errors="backslashreplace")` directly to avoid doing so. Thoughts?
=> Handle invalid UTF-8 string members

wlroots/ffi_build.py, wlroots/wlr_types/layer_shell_v1.py
These changes bring pywlroots in line with wlroots' 0.15 release. These
changes are the changes that may break users so let's wait until 0.15 is
released before merging and releasing these changes ourselves.
=> Add breaking changes for wlroots 0.15

tests/test_helper.py
Create a test for the helper script. Adding this provides some test coverage here and the import catches the previous problems with types annotations not working for Python versions <3.9.
=> Add test for helper

.github/workflows/ci.yml, wlroots/ffi_build.py, wlroots/wlr_types/surface.py, wlroots/xwayland.py
I'm playing around with XWayland, with the first step getting the C code compiled into the cffi. Unfortunately I've only got so far, so I am posting to see if you would have any ideas of how to fix the compilation errors.
There are a few `typedef`s that I've had to add, which I suspect are responsible. The full traceback I'm getting while building is:
```
Traceback (most recent call last):
File "/home/mcol/git/pywlroots/wlroots/ffi_build.py", line 2480, in <module>
ffi_builder.cdef(CDEF)
File "/usr/lib/python3.10/site-packages/cffi/api.py", line 112, in cdef
self._cdef(csource, override=override, packed=packed, pack=pack)
File "/usr/lib/python3.10/site-packages/cffi/api.py", line 126, in _cdef
self._parser.parse(csource, override=override, **options)
File …
```
=> Add xwayland C code

wlroots/xwayland.py
This seems to be needed to avoid a double free when exiting.
See https://github.com/flacjacket/pywlroots/pull/69#issuecomment-1018876414 for more info
=> Add destroy method to XWayland to release its pointer

.gitignore, wlroots/ffi_build.py
This updates the build step such that the wlroots version is fetched
from the compiled `lib` if it cannot be fetched from the system via
`ffi.verify`.
Similarly XWayland support is fetched from a local `_build.py` if it
cannot be determined with `ffi.verify`, which is generated during a
successful build.
Closes #77
=> Get build-time information from local files

wlroots/wlr_types/idle_inhibit_v1.py
According to wlroots' emitter for this signal, it *does* return the idle
inhibitor's `struct wlr_surface*`. However, in practice the pointed-to
data seems to be invalid, causing a crash (e.g.
https://github.com/qtile/qtile/issues/3361).
The data does not seem to be used by any compositor so until it is
needed we can probably get away without the wrapper, resolving the
problem.
=> Don't wrap IdleInhibitorV1's destroy event data

wlroots/ffi_build.py
On read-only file systems, `ffi.verify` fails:
```
OSError: [Errno 30] Read-only file system
```
This should catch that case in a similar fashion to PermissionError.
=> Catch OSErrors triggered by ffi_build.py version check

wlroots/xwayland.py
Restacking an XWayland surface does not require a sibling, and instead
it can be a null pointer, causing the window to restack to the top or
bottom of all windows.
=> XWayland surface restack sibling is optional

wlroots/ffi_build.py, wlroots/wlr_types/xcursor_manager.py
This adds the structs wlr_xcursor and wlr_xcursor_image, which lets a
compositor get an xcursor from the xcursor_manager and use it e.g. to
configure xwayland's default cursor image.
=> Expose xcursors to enable setting xwayland cursor images

wlroots/ffi_build.py, wlroots/wlr_types/virtual_pointer_v1.py
This adds objects from wlr_virtual_pointer_v1.h, letting client code use
this virtual pointer protocol.
=> Add wlr_virtual_pointer_v1 interface

wlroots/wlr_types/__init__.py
Apologies, I forgot to include this in the last patch. I added virtual_pointer while I was at it too because virtual_keyboard was bound, so I assumed it'd be better to be uniform.
=> [import] export_dmabuf and virtual_pointer support.

tiny/__main__.py, tiny/keyboard_handler.py, tiny/server.py, tiny/view.py
* Current signal implementation often does not work unless the frame
is focused. It also does not work if the frame is closed before the
SIGINT signal is sent.
* This commit uses the wayland event loop to incorporate the signal
handling directly in the compositor event loop.
Signed-off-by: Shinyzenith <aakashsensharma@gmail.com>
=> [update] improve SIGINT handler

wlroots/wlr_types/input_inhibit.py
These are needed so that compositors can get the identity of the client
that triggered the inhibitor
=> Expose input inhibitor activate/deactivate events

wlroots/wlr_types/foreign_toplevel_management_v1.py, wlroots/wlr_types/pointer_constraints_v1.py
These two wlroots enums are intended to be used as bit flags, supporting
0 or bitwise combinations of their values. Their current `IntEnum` base
class doesn't support either so let's convert to `IntFlag`.
=> Correct 2 enums to be IntFlags, supporting 0s

wlroots/wlr_types/input_device.py
It only has this one signal, for when the device is destroyed.
=> Add signals for wlr_input_device events

tiny/server.py, wlroots/ffi_build.py, wlroots/wlr_types/output.py, wlroots/wlr_types/output_layout.py, wlroots/wlr_types/output_management_v1.py
Properly adds `struct wlr_output_mode` and lets users iterate through
them from `Output`. Fixes the typing for a number of output-related
methods which may accept/return `NULL`s, so their types should reflect
that (`x | None`).
=> Fix up some output code

wlroots/ffi_build.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/cursor.py, wlroots/wlr_types/pointer.py, wlroots/wlr_types/pointer_gestures_v1.py
This lets compositors relay multi-finger touchpad events to clients. Similarly event classes in pointer.py are given getters to provide data from those events which are used by PointerGesturesV1.
=> Add handlers for wlr_pointer_gestures_v1

wlroots/wlr_types/data_device_manager.py
Drags provided by clients might not provide icons for rendering (e.g. google chrome), so trying to create Icons for ffi.NULL causes segfaults.
E.g. see https://github.com/qtile/qtile/issues/3894
=> Drag.icon can also return None if clients don't provide icons to render

tiny/server.py, wlroots/wlr_types/keyboard.py, wlroots/wlr_types/seat.py
- Check whether a keyboard is NULL before accessing its modifier state, to avoid a compositor crash
- drop the `keyboard.destroyed` property. It doesn't work if you have as the pointer being NULL is not the same as the wlr_keyboard being destroyed.
- make the return type of `seat.keyboard` `Keyboard | NULL` as a seat might not have an active keyboard.
=> Minor keyboard handling improvements

tiny/server.py, wlroots/ffi_build.py, wlroots/wlr_types/idle_notify_v1.py
I'm not sure how to test it except making `swayidle` run without complaining about the display not supporting idle protocol.
Should i commit the changes made to tiny ?
=> add idle_notify_v1 protocol.

README.rst
Update the url of the wlroots project. It migrated to gitlab.freedesktop.org in 2021.
=> Update wlroots url in README.rst

wlroots/ffi_build.py, wlroots/wlr_types/keyboard.py
[Sway](https://github.com/swaywm/sway/pull/2330) uses this function to configure the initial state of numlock/capslock.
Tested with Qtile.
Compositors would implement something similar to sway, like this to enable Numlock:
```py
mask = ffi.new("xkb_mod_mask_t *", 0)
one = ffi.new("uint32_t *", 1)
idx = ffi.new("xkb_mod_index_t *")
idx[0] = lib.xkb_keymap_mod_get_index(self.keyboard._ptr.keymap, ffi.new("const char []", "Mod2".encode("ascii")))
mask[0] |= one[0] << idx[0]
zero = ffi.new("uint32_t *", 0)           
lib.wlr_keyboard_notify_modifiers(self.keyboard._ptr, zero[0], zero[0], mask[0], zero[0])
``` 
the Capslock is named `Lock`.
My implementation is definitely not the best but it works.
I'm not sure if there's a way to do the same thing using pywlroots instead of copying sway's …
=> Expose `wlr_keyboard_notify_modifiers` function.

wlroots/backend.py, wlroots/wlr_types/output.py
Modify `Backend.start` and `Output.commit` to return boolean values rather than checking the return value and raising an error. Move the logic for the Pythonic APIs into the Python-specific functions, in particular the `__enter__` and `__exit__` so these objects will be well behaved when using the context manager.
Closes #135
Closes #136
=> Change some exceptions to return values

wlroots/ffi_build.py, wlroots/wlr_types/cursor.py, wlroots/wlr_types/seat.py, wlroots/wlr_types/touch.py
* Added class Touch similar to Pointer
* Renamed exceptions (put Event to the end)
* Added touch.h to ffi_build.py
=> Attempt to fix issue #133: Touch class

wlroots/wlr_types/seat.py
The property "has_grab" mirrors the method "keyboard_has_grab", but since there are several "_has_grab" functions, the user should call the specific method.
Fixes #147
=> Removed Seat property "has_grab" in favour of more explicit methods.

wlroots/ffi_build.py, wlroots/wlr_types/single_pixel_buffer_v1.py
Added wlr_types/single_pixel_buffer_v1 to support the single-pixel buffer protocol (part of wlroots since 0.16.0).
Fixes #155.
=> Added support for the Single-pixel buffer protocol.

wlroots/__init__.py
This helper function checks if the input is None and returns ffi.NULL, otherwise the _ptr attribute.
Closes #160.
=> Added helper function to return either _ptr attribute or ffi.NULL

wlroots/wlr_types/cursor.py
Also simplified the code by using the new ptr_or_null helper function.
=> Better error message: Use human readable name rather than a numeric constant.

wlroots/wlr_types/scene.py
Removed the RuntimeException in SceneOutput.commit() since it is a non-critical error. The boolean value should be sufficient and is closer to the wlroots API.
Closes #164.
=> SceneOutput.commit: Replaced exception with boolean value

tiny/server.py, wlroots/ffi_build.py, wlroots/wlr_types/__init__.py, wlroots/wlr_types/output.py, wlroots/wlr_types/output_management_v1.py
* Added OutputState to wlr_types/output.py
* Moved CustomMode from wlr_types/output_management_v1.py to wlr_types/output.py
* Added OutputHeadV1State.apply(OutputState) (closes #149)
* Fixed OutputHeadV1State.custom_mode setter (closes #170)
* Output.test() and Output.commit() accept an optional OutputState object
All changes should be backwards compatible.
=> Added support for OutputState

wlroots/wlr_types/cursor.py, wlroots/wlr_types/data_device_manager.py, wlroots/wlr_types/foreign_toplevel_management_v1.py, wlroots/wlr_types/idle_inhibit_v1.py, wlroots/wlr_types/layer_shell_v1.py, wlroots/wlr_types/pointer_constraints_v1.py, wlroots/wlr_types/seat.py, wlroots/wlr_types/xdg_activation_v1.py, wlroots/wlr_types/xdg_decoration_v1.py, wlroots/wlr_types/xdg_shell.py, wlroots/xwayland.py
=> Don't use deprecated surface module. Closes #176

wlroots/backend.py, wlroots/ffi_build.py
From wlroots 0.17 on, the multi-backend should be the default (for backends created with wlr_backend_autocreate()).
The "is_multi" property allows the caller to check if i.e. a vt-change is possible or not.
=> Added is_multi property to Backend

wlroots/wlr_types/xdg_shell.py
XdgTopLevel.parent returned always a parent even if the underlying _ptr.parent refers to NULL.
Replaced the check against None with a check against ffi.NULL.
Closes #183.
=> XdgTopLevel: Don't check parent pointer against None but ffi.NULL

.gitignore, wlroots/__init__.py, wlroots/ffi_build.py, wlroots/wlr_types/seat.py, wlroots/wlr_types/touch.py
* Added missing event declarations to Touch
* Added SeatTouchState
* Added Seat.touch_send_* methods
* Fixed return type of Seat.touch_notify_down
* Added helper function to pywlroots that retuns an instance of the provided type or None
=> Fixed touch support

CHANGES.rst, wlroots/wlr_types/seat.py
touch_point_clear_focus took too many arguments like ``surface`` and the surface coordinates. Aligned the signature to wlr_seat_touch_point_clear_focus.
Closes #189
=> Fixed signature of Seat.touch_point_clear_focus

wlroots/renderer.py
autocreate() checked the return value of lib.wlr_renderer_autocreate() against a truth value not ffi.NULL.
* Check explitely against ffi.NULL
* Replaced exceptions from render_texture and render_texture_with_matrix with boolean values
Closes #195
=> Fixed Renderer.autocreate() return value check

.github/workflows/release.yml
I was testing the workflows the other day and realize that pypy 3.9 was always failing. I did a research and found out that support for 3.9 was drop. See [PyPy anouncement](https://doc.pypy.org/en/latest/release-v7.3.17.html#pypy-versions-and-speed-pypy-org) and [manylinux anouncement](https://github.com/pypa/manylinux/issues/1680).
=> fix: remove pypy in python version 3.9

dist-build-constraints.txt
This is a version problem, manylinux_2_28 is based on AlmaLinux 8 ([reference](https://github.com/pypa/manylinux/blob/main/README.rst#manylinux_2_28-almalinux-8-based)).
AlmaLinux 8 uses version 0.9 for libxkbcommon ([reference](https://repo.almalinux.org/almalinux/8/AppStream/x86_64/os/Packages/)) which is lower than the target version of python-xkbcommon which is 1.0.1
=> fix: xkbcommon error

wlroots/ffi_build.py, wlroots/xwayland.py
Add missing `xcb_icccm_wm_hints_t *hints` pointer and the attribute `hints->flags` from the wlroots C source code to this repo.
EDIT: This is incomplete, please read next comment.
=> Add xcb_icccm_wm_hints_t attributes

pyproject.toml
See warning:
```
/usr/lib/python3.13/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
!!
corresp(dist, value, root_dir)
```
=> fix: use SPDX license expression, avoid deprecation

tiny/server.py
The data field is not being set for toplevels, so when it needs to be accessed for popup handling, an error occurs. This pull request adds a line to set the data field for toplevels, preventing the error.
=> fix tinywl popup handling

.github/workflows/ci.yml, .github/workflows/release.yml
Fix this warning:
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
=> fix: 'meson build' deprecation

wlroots/xwayland.py
wlroots wants to fork() and waitpid() on the result:
https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/871646d22522141c45db2c0bfa1528d595bb69df
(this code *almost* does the right thing, but only does SIG_BLOCK in the first fork, not the parent...)
applications using wlroots which have SIGCHLD handlers installed may interfere with this, so expose the server pid so they can use WNOWAIT trickery to avoid reaping this pid, to allow wlroots to do so.
Maybe this is the wrong patch to fix the described issue: maybe pywayland should block SIGCHLD (via signal.pthread_sigmask(), since applications may be multithreaded, especially if they use asyncio) and then do wlr_xwayland_server_create(), then unblock it for users? But either way, seems like people might want to see the pid here.
=> expose xwayland.Server's pid
